name       : recoll
version    : 1.34.0
release    : 29
source     :
    - https://www.lesbonscomptes.com/recoll/recoll-1.34.0.tar.gz : 7baeaac2c79dcbff6d866f986c2d538603f25378dd71862f2cb7e775c6594668
homepage   : https://www.lesbonscomptes.com/recoll/
license    : GPL-2.0-or-later
component  : desktop
summary    : Recoll is a desktop full-text search tool
description: |
    Recoll finds keywords inside documents as well as file names.
builddeps  :
    - pkgconfig(Qt5WebKit)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
    - chmlib-devel
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %configure --without-aspell --without-fam --disable-python-aspell
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
