name       : recoll
version    : 1.24.1
release    : 9
source     :
    - https://www.lesbonscomptes.com/recoll/recoll-1.24.1.tar.gz : 1d6433cd79fc25fc2941620eba8be934629189fd078c8b8a4028a301bc7f75eb
license    : GPL-2.0-or-later
component  : desktop
summary    : Recoll is a desktop full-text search tool
description: |
    Recoll finds keywords inside documents as well as file names.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(ice)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %patch -p1 < $pkgfiles/0001-Patch-for-qt.patch

    %configure --without-aspell
build      : |
    %make
install    : |
    %make_install
