name       : recoll
version    : 1.23.2
release    : 6
source     :
    - https://www.lesbonscomptes.com/recoll/recoll-1.23.2.tar.gz : 0e93e6be0dc2225b03a4850887bd29da47a61e07652fde51be254ef9f8310048
license    : GPL-2.0
component  : desktop
summary    : Recoll finds keywords inside documents as well as file names
description: |
    Recoll finds keywords inside documents as well as file names
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ice)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %configure --without-aspell
build      : |
    %make
install    : |
    %make_install
