name       : recoll
version    : 1.32.5
release    : 28
source     :
    - https://www.lesbonscomptes.com/recoll/recoll-1.32.5.tar.gz : 52f4692646a937d9d71f2dd363b495759feccbc7f74021e4837fc5334a0ff556
homepage   : https://www.lesbonscomptes.com/recoll/
license    : GPL-2.0-or-later
component  : desktop
summary    : Recoll is a desktop full-text search tool
description: |
    Recoll finds keywords inside documents as well as file names.
builddeps  :
    - pkgconfig(Qt5WebKit)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
    - chmlib-devel
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %configure --without-aspell --without-fam
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
