name       : recoll
version    : 1.22.3
release    : 1
source     :
    - http://www.lesbonscomptes.com/recoll/recoll-1.22.3.tar.gz : 7495a6bcd2cea033949333870200161638bc36034057063902c911aafda3591c
license    : GPL-2.0
component  : desktop
summary    : Recoll finds keywords inside documents as well as file names
description: |
    Recoll finds keywords inside documents as well as file names
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ice)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %configure --without-aspell
build      : |
    %make
install    : |
    %make_install
