name       : recoll
version    : 1.31.0
release    : 23
source     :
    - https://www.lesbonscomptes.com/recoll/recoll-1.31.0.tar.gz : 4ed91fa21cde4f41ceeb2c0230dc6b3835b50e7260e4a305931f406c37d0b7e7
homepage   : https://www.lesbonscomptes.com/recoll/
license    : GPL-2.0-or-later
component  : desktop
summary    : Recoll is a desktop full-text search tool
description: |
    Recoll finds keywords inside documents as well as file names.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - pkgconfig(xapian-core)
    - chmlib-devel
rundeps    :
    - djvulibre
    - ghostscript
    - mutagen
    - perl-image-exiftool
    - poppler-utils
    - python-chardet
    - python-rarfile
setup      : |
    %configure --without-aspell --without-fam
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
